#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 05, 2017 08:11:49 PM


import sys
from PIL.ImageTk import PhotoImage
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global op_dijkstra
    op_dijkstra = StringVar()
    global op_origem
    op_origem = StringVar()
    global op_destino
    op_destino = StringVar()
    global op_orig_dest
    op_orig_dest = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None



def processar():
    pass

if __name__ == '__main__':
    import simulador2
    simulador2.vp_start_gui()


